### ISSUE TITLE
最新，最热，沙发，精华 下面所有 帖子的列表项  快速点击2下，会出现2个页面覆盖，2个一样activity在栈顶，需要back2次才能返回。

### ISSUE THREAD

**Issue by Hevinwen** [testerhome/A-Native-TesterHome#10]
最新，最热，沙发，精华 下面所有 帖子的列表项  快速点击2下，会出现2个页面覆盖，2个一样activity在栈顶，需要back2次才能返回， 应该将activity启动模式更换成singleTop模式 或者  在响应点击事件的时候做个时间间隔的判断.

**Comment by sxyy** [comment]
1.0.4版本已解决

**Comment by vclub** [comment]
如果已经修复 那我就关闭了
