### ISSUE TITLE
回复里面的图片会掩盖掉文字

### ISSUE THREAD

**Issue by lihuazhang** [testerhome/A-Native-TesterHome#3]
如图，建议修改，图片单独放在一行。

![image](https://cloud.githubusercontent.com/assets/872749/10956364/0874fa1e-8396-11e5-81b4-e8b4f8ac5f4c.png)

**Comment by vclub** [comment]
嗯 现在只是显示了，还没有处理好，
不过你旋转一下 应该能正常显示，呵呵

**Comment by sxyy** [comment]
通过添加RichText控件 解决此问题。
